config/routes.rb
Rails.application.routes.draw do
  get 'relationships/follows'
  get 'relationships/followers'
  
  devise_for :users

  resources :books do 
    resource :favorites, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end

  resources :users,only: [:show,:index,:edit,:update] do
    resource :relationship, only: [:create, :destroy, :follows, :followers]
  end

  root 'home#top'
  get 'home/about' => "home#about"
  post 'search/target_select' => "search#target_select"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable,:validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy

  #==========================自分がフォローしているユーザとの関連============================================================================== 
  has_many :active_relationships, class_name: "Relationship", foreign_key: :following_id
  has_many :followings, through: :active_relationships, source: :follower
  # =====================================================================================================================================

  # =========================自分がフォローされているユーザとの関連============================================================================
  has_many :passive_relationships, class_name: "Relationship", foreign_key: :follower_id
  has_many :followers, through: :passive_relationships, source: :following
  # =====================================================================================================================================

  attachment :profile_image

  #バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
  validates :name, length: {maximum: 20, minimum: 2}
  validates :introduction, length: {maximum: 50}

  def followed?(user)
    passive_relationships.where(following_id: user.id).exists?
  end

  def self.method_select(method,word)
    if method == "forward_match"
        @users = User.where("name LIKE ?","#{word}%")
    elsif method == "backward_match"
        @users = User.where("name LIKE ?","%#{word}")
    elsif method == "perfect_match"
        @users = User.where("name LIKE ?","#{word}")
    elsif method == "partial_match"
        @users = User.where("name LIKE ?","%#{word}%")
    else
        @users = User.all
    end
  end


end

# belongs_to :user
# belongs_to :following, class_name: "User" 
# belongs_to :follower, class_name: "User" 

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :baria_user, only: [:update, :edit]
	before_action :authenticate_user!

  def show
  	@user = User.find(params[:id])
  	@books = @user.books
  	@book = Book.new #new bookの新規投稿で必要（保存処理はbookコントローラー側で実施）
  end

  def index
	if @users = session[:word_params]
		@users = User.method_select(session[:method_params],session[:word_params])
	else
		@users = User.all
	end
	# session[:word_params].clear  .nilだと空の値が残るがdeleteだとsession自体が削除される
	session.delete(:method_params)
	session.delete(:word_params)
	@user = current_user
	@book = Book.new
  end

  def edit
	  @user = User.find(params[:id])
  end

  def update
  	@user = User.find(params[:id])
	  if @user.update(user_params)
  		redirect_to user_path(@user), notice: "successfully updated user!"
	  else
  		render "edit"
  	end
  end

  private
  def user_params
  	params.require(:user).permit(:name, :introduction, :profile_image)
  end

  #url直接防止　メソッドを自己定義してbefore_actionで発動。
#    def baria_user
#   	unless params[:id].to_i == current_user.id
#   		redirect_to user_path(current_user)
#   	end
#    end
   def baria_user
	user = User.find(params[:id])
	if user != current_user
		redirect_to user_path(current_user)
	end
 end
 

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow.html.erb
<% if @user.followed?(current_user) %>
    <div class="row">
        <%= link_to user_relationship_path(@user), method: :delete, class:"btn btn-primary btn-block" do %>
            <span>フォローを解除する</span>
        <% end %>
    </div>
<% else %>
    <div class="row">
        <%= link_to user_relationship_path(@user), method: :post, class:"btn btn-primary btn-block" do %>
            <span>フォローする</span>
        <% end %>
    </div>
<% end %>

app/views/users/_profile.html.erb
<table class="table">
		<tr><%= attachment_image_tag(@user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg") %></tr>

		<tr>
			<th>name</th>
			<td><%= @user.name %></td>
		</tr>

		<tr>
			<th>introduction</th>
			<td><%= @user.introduction %></td>
		</tr>
		<tr>
			<th>follows</th>
			<td>
				<%= link_to relationships_follows_path do %>
					<%= @user.followings.count %>
				<% end %>
			</td>
		</tr>
		<tr>
			<th>followers</th>
			<td>
				<%= link_to relationships_followers_path do %>
					<%= @user.followers.count %>
				<% end %>
			</td>
		</tr>
</table>

<div class="row">
	<%= link_to '',edit_user_path(@user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_@user_#{@user.id}" %>
</div>

app/views/users/edit.html.erb
<h2>User info</h2>

<%= form_for(@user) do |f| %>

<!-- エラーメッセージ表示-->
<% if @user.errors.any? %>
	<h3><%= @user.errors.count %>error occurrence</h3><!--エラーメッセ-->
	<ul>
		<% @user.errors.full_messages.each do |message| %>
		<li><%= message %></li>
		<% end %>
	</ul>
<% end %>
<!-- エラーメッセージ表示-->

<div class="field">
	<%= f.label :name %>
	<%= f.text_field :name, class: "name" %>
</div>

<div class="field">
	<%= f.label :image %>
	<%= f.attachment_field :profile_image, class: "user_image" %>
</div>

<div class="field">
	<%= f.label :introduction %>
	<%= f.text_area :introduction, class: "introduction" %>
</div>

<div class="actions">
	<%= f.submit %>
</div>

<% end %>

app/views/users/index.html.erb
<%= render "layouts/search" %>
<div class="row">
	<div class="col-xs-3">

		<h2>User info</h2>
		<%= render 'users/profile', user: current_user %>
		<!--メモ　右側の指定に注意。そこを間違えるとエラーが発生して表示されない -->

		<h2>New book</h2>
		<%= render 'books/newform', book: @book %>

	</div>
	<div class="col-xs-9">


		<h2>Users</h2>
		<!--users一覧 -->
		<table class="table">
			<thead>
				<tr>
					<th>image</th>
					<th>name</th>
					<th>follows</th>
					<th>followers</th>
					<th colspan="3"></th>
				</tr>
			</thead>

			<tbody>
				<% @users.each do |user| %>
				<tr>
					<td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>
					<td><%= user.name%></td>
					<td>
						<%= user.followings.count %>
					</td>
					<td>
						<%= user.followers.count %>
					</td>
					<td>
						<% if user.followed?(current_user) %>
							<%= link_to user_relationship_path(user), method: :delete, class:"btn btn-primary btn-xs" do %>
								<span>フォローを解除する</span>
							<% end %>
						<% else %>
							<%= link_to user_relationship_path(user), method: :post, class:"btn btn-primary btn-xs" do %>
								<span>フォローする</span>
							<% end %>
						<% end %>
					</td>
					<td><%= link_to "Show", user, class: "user_#{user.id}" %></td>
				</tr>
				<% end %>
			</tbody>
		</table>
		<!--users一覧 -->

	</div>
</div>

app/views/users/show.html.erb
<div class="row">
	<div class="col-xs-3">

		<h2>User info</h2>
		<%= render 'users/profile', user: @user %>
		<!--同コントローラーのviewで表示ならusersは省略可 -->

		<h2>User info</h2>
		<%= render "users/follow" %>

		<h2>New book</h2>
		<%= render 'books/newform', book: @book %>

	</div>
	<div class="col-xs-9">

		<h2>Books</h2>
		<!--books一覧 -->
		<table class="table table-hover table-inverse">
			<thead>
				<tr>
					<th></th>
					<th>Title</th>
					<th>Opinion</th>
					<th colspan="3"></th>
				</tr>
			</thead>

			<tbody>
				<% @books.each do |book| %>
				<tr>
					<td>
						<%= link_to (book.user) do %>
						<%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
						<% end %>
					</td>
					<td><%= link_to book.title,book, class: "book_#{book.id}" %></td>
					<td><%= book.body %></td>
				</tr>
				<% end %>
			</tbody>
		</table>
		<!--books一覧 -->

	</div>
</div>