config/routes.rb
Rails.application.routes.draw do
  get 'relationships/follows'
  get 'relationships/followers'
  
  devise_for :users

  resources :books do 
    resource :favorites, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end

  resources :users,only: [:show,:index,:edit,:update] do
    resource :relationship, only: [:create, :destroy, :follows, :followers]
  end

  root 'home#top'
  get 'home/about' => "home#about"
  post 'search/target_select' => "search#target_select"
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	has_many :favorites, dependent: :destroy
	has_many :comments, dependent: :destroy
	#バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
	#presence trueは空欄の場合を意味する。
	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}

    def favorited_by?(user)
        favorites.where(user_id: user.id).exists?
	end
	
	def self.method_select(method,word)
		if method == "forward_match"
			@books = Book.where("title LIKE ?","#{word}%")
		elsif method == "backward_match"
			@books = Book.where("title LIKE ?","%#{word}")
		elsif method == "perfect_match"
			@books = Book.where("title LIKE ?","#{word}")
		elsif method == "partial_match"
			@books = Book.where("title LIKE ?","%#{word}%")
		else
			@books = Book.all
		end
	end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update, :destroy]

  def show
	  @book = Book.find(params[:id])
	  @user = @book.user
	  @comment = Comment.new
	  @comments = @book.comments
	#   @comment_user = @book.comments.includes(:user).first
	  session[:favorite] = "show"
  end

  def index
	if @books = session[:word_params]
		@books = Book.method_select(session[:method_params],session[:word_params])
	else
		@books = Book.all
	end
	session.delete(:word_params)
	@book = Book.new
	@user = current_user
	session[:favorite] = "index"
  end

  def create
	@book = Book.new(book_params) #Bookモデルのテーブルを使用しているのでbookコントローラで保存する。
	@book.user = current_user
  	if @book.save #入力されたデータをdbに保存する。
  		redirect_to @book, notice: "successfully created book!"#保存された場合の移動先を指定。
  	else
		@books = Book.all
		@user = current_user
  		render 'index'
  	end
  end

  def edit
  	@book = Book.find(params[:id])
  end



  def update
  	@book = Book.find(params[:id])
  	if @book.update(book_params)
  		redirect_to @book, notice: "successfully updated book!"
  	else #if文でエラー発生時と正常時のリンク先を枝分かれにしている。
  		render "edit"
  	end
  end

  def destroy
  	@book = Book.find(params[:id])
  	@book.destroy
  	redirect_to books_path, notice: "successfully delete book!"
  end

  private

  def book_params
  	params.require(:book).permit(:title, :body)
  end

  def correct_user
	book = Book.find(params[:id])
	user = book.user
	if user != current_user
		redirect_to books_path
	end
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_newcomment.html.erb
<%= form_for @comment, url:book_comments_path(@book) do |f| %>
    <div class="row">
        <%= f.text_area :comment, class:"col-xs-12" %>
    </div>

    <div class="actions row">
        <%= f.hidden_field :@comment, :value => @comment %>
        <%= f.submit "Add Comment", class:"btn btn-primary btn-block" %>
    </div>
<% end %>

app/views/books/_newform.html.erb
<%= form_for(@book) do |f| %>

	<div class="field row">
		<%= f.label :title %>
		<%= f.text_field :title, class: "col-xs-12 book_title" %>
	</div>

	<div class="field row">
		<%= f.label :opinion %> <!-- ここを変更 -->
		<%= f.text_area :body, class: "col-xs-12 book_body" %>
	</div>

	<div class="actions row">
		<%= f.submit class: "btn btn-primary col-xs-12" %>
	</div>
<% end %>

app/views/books/edit.html.erb
<% if @book.errors.any? %>
	<h3><%= @book.errors.count %>error occurrence</h3><!--エラーメッセ-->
	<ul>
		<% @book.errors.full_messages.each do |message| %>
		<li><%= message %></li>
		<% end %>
	</ul>
<% end %>
<div class="row">
<div class="col-md-6 col-md-offset-3">

<h1>Editing Book</h1>

<%= render "books/newform", book: @book %>
<%= link_to "Show", @book, class: "book_#{@book.id}" %>
<%= link_to "Back", books_path, class: "back" %>

</div>
<div class="col-md-3"></div>

</div>

app/views/books/index.html.erb
<%= render "layouts/search" %>
<% if @book.errors.any? %>
	<h3><%= @book.errors.count %>error occurrence</h3><!--エラーメッセ-->
	<ul>
		<% @book.errors.full_messages.each do |message| %>
		<li><%= message %></li>
		<% end %>
	</ul>
<% end %>
<div class="row">
	<div class="col-xs-3">

		<h2>User info</h2>
		<%= render 'users/profile', user: current_user %>
		<!--メモ　右側の指定に注意。そこを間違えるとエラーが発生して表示されない -->

		<h2>New book</h2>
		<%= render 'books/newform', book: @book %>

	</div>

	<div class="col-xs-9">
		<h2>Books</h2>
		<!--books一覧 -->
		<table class="table table-hover table-inverse">
			<thead>
				<tr>
					<th></th>
					<th>Title</th>
					<th>Opinion</th>
					<th>Engagement</th>
					<th>Comment</th>
					<%# <th colspan="3"></th> %>
				</tr>
			</thead>

			<tbody>
				<% @books.each do |book| %>
				<tr>
					<td>
						<%= link_to(book.user) do %>
						<%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
						<% end %>
					</td>
					<td><%= link_to book.title, book, class: "book_#{book.id}" %></td>
					<td><%= book.body %></td>
					<td>
						<%# favorite機能 %>
						<% if book.favorited_by?(current_user) %>
							<%= link_to book_favorites_path(book), method: :delete do %>
								<i class="fas fa-heart"></i>
								<%= book.favorites.count %>
							<% end %>

						<% else %>
						<%# pathでpostする方法も確認すること %>
						<%# <span>お気に入り登録: </span><%= link_to @book.favorites.count, book_favorites_path(@book), method: :post %>
						<%# <%= link_to "♡", "#{@book.id}/favorites", method: :post %>
							<%= link_to book_favorites_path(book), method: :post do %>
								<i class="far fa-heart"></i>
								<%= book.favorites.count %>
							<% end %>
						<% end %>
					</td>
					<td>
					<%= book.comments.count %>
					</td>
				</tr>
				<% end %>
			</tbody>
		</table>

		<!--books一覧 -->


	</div>
</div>

app/views/books/show.html.erb
<% if @comment.errors.any? %>
    <h3><%= @comment.errors.count %>error occurrence</h3>
    <ul>
        <% @comment.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
    </ul>
<% end %>
<div class="row">
	<div class="col-xs-3">

		<h2>User info</h2>
		<%= render 'users/profile' %>

		<h2>New book</h2>
		<%= render 'books/newform' %>

		<h2>New Comment</h2>
		<%= render "books/newcomment" %>

	</div>

	<div class="col-xs-9">
		<h2>Book detail</h2>

		<table class="table">
			<tr>
				<td>
					<%= link_to (@book.user) do %>
					<%= attachment_image_tag(@book.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %><br>
					<%= @book.user.name %>
					<% end %>
				</td>
				<td><%= link_to @book.title, @book %></td>
				<td><%= @book.body %></td>
				<% if @book.user == current_user %>
				<td><%= link_to "Edit",edit_book_path(@book), class: "btn-sm btn-success edit_book_#{@book.id}" %></td>
				<td><%= link_to "Destroy",@book, method: :delete, data: {confirm: "本当に削除してもよろしいですか？"}, class: "btn-sm btn-danger destroy_book_#{@book.id}" %></td>
				<% end %>
				<td>
					<%# favorite機能 %>
					<% if @book.favorited_by?(current_user) %>
						<%= link_to book_favorites_path(@book), method: :delete do %>
							<i class="fas fa-heart"></i>
							<%= @book.favorites.count %>
						<% end %>

					<% else %>
						<%= link_to book_favorites_path(@book), method: :post do %>
							<i class="far fa-heart"></i>
							<%= @book.favorites.count %>
						<% end %>
					<% end %>
				</td>
				<td>
				<span class="h6">Comment: </span><span><%= @comments.count %></span>
				</td>
			</tr>
		</table>
	</div>
	<div class="col-xs-9">
		<table class="table">
		<h2>Comment</h2>
		<% @comments.each do |comment| %>
			<tr>
			<td class="col-xs-1">
				<%#= @comment_user.user.name %>
				<div><%= attachment_image_tag(comment.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></div>
				<%= comment.user.name %>
			</td>
			<td class="col-xs-9">
				<%= comment.comment %>
			</td>
			<td class="col-xs-2 text text-right">
				<%= link_to "Destroy", book_comment_path(@book, comment), method: :delete, class:"btn btn-danger btn-xs" %>
			</td>
			</tr>
		<% end %>
		</table>
	</div>

</div>