config/routes.rb
Rails.application.routes.draw do
  get 'relationships/follows'
  get 'relationships/followers'
  
  devise_for :users

  resources :books do 
    resource :favorites, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end

  resources :users,only: [:show,:index,:edit,:update] do
    resource :relationship, only: [:create, :destroy, :follows, :followers]
  end

  root 'home#top'
  get 'home/about' => "home#about"
  post 'search/target_select' => "search#target_select"
end

app/views/layouts/_search.html.erb
<% if user_signed_in? %>
    <div class="row search">

        <%# <div class="col-xs-12 text text-right">form_with</div> %>
        <%= form_with(url: search_target_select_path, method: :post, local: true, class:"col-xs-12 text text-right") do |f| %>
            <%= f.select :target, ["Users","Books"] %>
            <%= f.select :method, ["forward_match","backward_match","perfect_match","partial_match"] %>
            <%#= f.select :method, [["前方一致","forward_match"], ["後方一致","backward_match"], ["完全一致","perfect_match"], ["部分一致","partial_match"]] %>
            <%= f.text_field :word %>
            <%= f.submit "search" %>
        <% end %>

        <%# <div class="col-xs-12 text text-right">form_tag</div> %>
        <%#= form_tag(users_path, :method => 'get', class:"col-xs-12 text text-right" ) do %>
            <%#= select_tag :select => "Users""Books" %>
            <%#= text_field_tag :search %>
            <%#= submit_tag 'Search', :name => nil %>
        <%# end %>

    </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/0141f0daaa.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!--ヘッダーの記述-->
    <%# <header class="navbar navbar-fixed-top navbar-default"> %>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">

        <nav class="nav navbar-nav navbar-left">
          <span>Bookers</span>
        </nav>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <!--if文でサインインとアウト時の表示を変更-->
            <% if user_signed_in? %>
            <li><%= link_to ' Home', user_path(current_user), class: 'glyphicon glyphicon-home home' %></li>
            <li><%= link_to ' Users', users_path, class: 'glyphicon glyphicon-user users' %></li>
            <li><%= link_to ' Books', books_path, class: 'glyphicon glyphicon-book books' %></li>
            <%# <a href="<%= destroy_user_session_path" data-method="delete" class="glyphicon glyphicon-log-out" aria-hidden="true"> logout</a> %>
            <li><%= link_to ' logout', destroy_user_session_path, method: :delete, class: 'glyphicon glyphicon-log-out logout' %></li>
            <% else %>
            <li><%= link_to ' Home', root_path, class: 'glyphicon glyphicon-home home' %></li>
            <li><%= link_to ' About', home_about_path, class: 'glyphicon glyphicon-link about' %></li>
            <li><%= link_to ' sign up', new_user_registration_path, class: 'glyphicon glyphicon-edit sign_up' %></li>
            <li><%= link_to ' login', new_user_session_path, class: 'glyphicon glyphicon-log-in sign_in' %></li>
            <% end %>
          </ul>
        </nav>

      </div>
    </header>
    <!--ヘッダーの記述-->
    <div class="container">
        <br><p id="notice"><%= notice %></p> <!--デバイスでnotice設定されているので呼び出してるだけ-->

      <%= yield %>
      <%# フッダー %>
      <div class="row">
        <div class="col-xs-12">
          <div class="text text-right">CopyRight Infratop.inc</div>
        </div>
      </div>

    </div>
  </body>
</html>